#!/usr/bin/env python3
"""Tests for the sprite build step.

The real inputs are Wube's artwork, which cannot be committed and cannot reach
CI, so everything here runs against a synthetic extract the test builds itself:
the same index shapes the extractor writes, with sheets generated by the
project's own PNG writer. That proves the pipeline without the game.
"""
import importlib.util
import json
import os
import shutil
import tempfile
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


png = _load("chartorio_png", os.path.join(ROOT, "render", "png.py"))
build = _load("chartorio_build", os.path.join(ROOT, "render", "build.py"))


def sheet(width, height, seed=0):
    """A sheet where every pixel differs, so a wrong crop cannot pass."""
    out = bytearray()
    for y in range(height):
        for x in range(width):
            out += bytes(((x * 7 + seed) % 256, (y * 11 + seed) % 256,
                          (x * y + seed) % 256, 255))
    return png.write(width, height, 4, bytes(out))


class Extract:
    """A synthetic extract with one of every shape the extractor produces."""

    def __init__(self, root):
        self.root = root
        os.makedirs(root, exist_ok=True)
        # Scaled down from the real shapes: the relationships are what matter,
        # and a pure Python PNG writer is slow enough that realistic sheets
        # would put twenty seconds into every CI run.
        self.write("furnace.png", sheet(128, 64, 1))       # animation, frame 0 drawn
        self.write("drill-n.png", sheet(64, 64, 2))        # one direction of many
        self.write("belt.png", sheet(128, 160, 3))         # a grid, addressed at draw time
        self.write("ore.png", sheet(128, 128, 4))          # a grid
        self.write("grass.png", sheet(512, 72, 5))         # tile, one row drawn
        self.write("icon.png", sheet(120, 64, 6))          # icon plus mipmaps
        self.write("shared.png", sheet(256, 128, 7))       # two prototypes, same corner
        self.write("orphan.png", sheet(64, 64, 8))         # referenced by nothing
        index = {
            "version": 1, "pixels_per_tile": 32,
            "sprites": {
                "furnace": {"kind": "static", "category": "furnace", "layers": [
                    {"file": "furnace.png", "width": 40, "height": 34,
                     "scale": 0.5, "shift": [0, 0], "x": 0, "y": 0}]},
                "drill": {"kind": "directional", "category": "mining-drill", "by": {
                    "0": [{"file": "drill-n.png", "width": 48, "height": 52,
                           "scale": 0.5, "shift": [0, 0], "x": 0, "y": 0}]}},
                "belt": {"kind": "belt", "category": "transport-belt", "layers": [
                    {"file": "belt.png", "width": 128, "height": 128,
                     "scale": 0.5, "shift": [0, 0], "x": 0, "y": 0, "frames": 16}]},
                "iron-ore": {"kind": "ore", "category": "resource",
                             "stage_counts": [100], "layers": [
                    {"file": "ore.png", "width": 128, "height": 128,
                     "scale": 0.5, "shift": [0, 0], "x": 0, "y": 0,
                     "variation_count": 8}]},
                "spawner": {"kind": "static", "category": "unit-spawner", "layers": [
                    {"file": "shared.png", "width": 130, "height": 94,
                     "scale": 0.5, "shift": [0, 0], "x": 0, "y": 0}]},
                "spawner-two": {"kind": "static", "category": "unit-spawner", "layers": [
                    {"file": "shared.png", "width": 130, "height": 94,
                     "scale": 0.5, "shift": [0, 0], "x": 0, "y": 0}]},
            },
            "tiles": {"grass-1": {"file": "grass.png", "cell": 8, "count": 16,
                                  "line_length": 16, "x": 0, "y": 0, "scale": 0.5}},
            "items": {"coal": {"file": "icon.png", "size": 64}},
        }
        with open(os.path.join(root, "index.json"), "w") as handle:
            json.dump(index, handle)

    def write(self, name, data):
        with open(os.path.join(self.root, name), "wb") as handle:
            handle.write(data)


class BuildStep(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.source = os.path.join(self.dir, "extract")
        self.target = os.path.join(self.dir, "built")
        Extract(self.source)
        self.record = build.build(self.source, self.target)

    def tearDown(self):
        shutil.rmtree(self.dir, ignore_errors=True)

    def size(self, root, name):
        return os.path.getsize(os.path.join(root, name))

    def read(self, root, name):
        with open(os.path.join(root, name), "rb") as handle:
            return handle.read()

    def test_the_build_is_smaller(self):
        self.assertLess(self.record["bytes_out"], self.record["bytes_in"])

    def test_the_extract_is_never_written_to(self):
        # The whole point of extracting unchanged is that it stays checkable.
        self.assertEqual(self.size(self.source, "furnace.png"), len(sheet(128, 64, 1)))
        with open(os.path.join(self.source, "index.json")) as handle:
            self.assertEqual(json.load(handle)["sprites"]["furnace"]["layers"][0]["x"], 0)

    def test_a_frame_is_cut_out_of_an_animation_sheet(self):
        width, height, _, _ = png.read(self.read(self.target, "furnace.png"))
        self.assertEqual((width, height), (40, 34))

    def test_a_grid_sheet_survives_whole(self):
        # A belt steps through sixteen frames across twenty orientations, and
        # ore across richness by variation. Cropping either breaks it.
        for name, expect in (("belt.png", (128, 160)), ("ore.png", (128, 128))):
            width, height, _, _ = png.read(self.read(self.target, name))
            self.assertEqual((width, height), expect, name)

    def test_a_tile_keeps_only_its_size_one_row(self):
        width, height, _, _ = png.read(self.read(self.target, "grass.png"))
        self.assertEqual((width, height), (16 * 8, 8))

    def test_an_icon_loses_its_mipmaps(self):
        width, height, _, _ = png.read(self.read(self.target, "icon.png"))
        self.assertEqual((width, height), (64, 64))

    def test_a_shared_sheet_is_cropped_when_both_want_the_same_corner(self):
        width, height, _, _ = png.read(self.read(self.target, "shared.png"))
        self.assertEqual((width, height), (130, 94))

    def test_a_file_nothing_references_is_dropped(self):
        self.assertIn("orphan.png", self.record["dropped"])
        self.assertFalse(os.path.exists(os.path.join(self.target, "orphan.png")))

    def test_offsets_are_rewritten_to_the_new_origin(self):
        # A sprite cropped correctly but still addressed at its old offset
        # draws from somewhere else entirely.
        with open(os.path.join(self.target, "index.json")) as handle:
            index = json.load(handle)
        self.assertEqual(index["tiles"]["grass-1"]["x"], 0)
        self.assertEqual(index["sprites"]["furnace"]["layers"][0]["x"], 0)

    def test_verify_passes_on_a_good_build(self):
        checked, problems = build.verify(self.source, self.target)
        self.assertEqual(problems, [])
        self.assertGreater(checked, 0)

    def test_verify_catches_a_mangled_sprite(self):
        # The failure that matters: smaller, but drawing the wrong thing.
        with open(os.path.join(self.target, "furnace.png"), "wb") as handle:
            handle.write(sheet(40, 34, 99))
        _, problems = build.verify(self.source, self.target)
        self.assertTrue(any("furnace.png" in p for p in problems), problems)

    def test_verify_catches_the_extract_changing_underneath(self):
        with open(os.path.join(self.source, "furnace.png"), "wb") as handle:
            handle.write(sheet(128, 64, 42))
        _, problems = build.verify(self.source, self.target)
        self.assertTrue(any("changed under the build" in p for p in problems), problems)

    def test_building_again_gives_the_same_bytes(self):
        again = os.path.join(self.dir, "again")
        second = build.build(self.source, again)
        self.assertEqual(self.record["bytes_out"], second["bytes_out"])
        for name in os.listdir(self.target):
            if name.endswith(".png"):
                self.assertEqual(self.size(self.target, name), self.size(again, name), name)

    def test_the_manifest_says_where_it_came_from(self):
        with open(os.path.join(self.target, build.MANIFEST)) as handle:
            record = json.load(handle)
        self.assertEqual(record["source"], os.path.abspath(self.source))
        self.assertIn("sha256", record["files"]["furnace.png"])
        self.assertTrue(record["settings"]["crop"])

    def test_no_crop_copies_everything_whole(self):
        plain = os.path.join(self.dir, "plain")
        build.build(self.source, plain, crop=False)
        width, height, _, _ = png.read(self.read(plain, "furnace.png"))
        self.assertEqual((width, height), (128, 64))


if __name__ == "__main__":
    unittest.main()
